baseURL = 'https://www.o-unit.net/'
defaultContentLanguage="ja"
locale = 'ja'
title = 'o-unit - ずっと建築中 -'
[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime"]
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/gohugo-ananke/ananke/v2'

[[menu.main]]
  identifier = "minecraft"
  name = "Minecraft"
  url = "/minecraft/"
  weight = 10
[[menu.main]]
  identifier = "iidx"
  name = "IIDX"
  url = "/iidx/"
  weight = 20
[[menu.main]]
  identifier = "homeserver"
  name = "自宅サーバ"
  url = "/homeserver/"
  weight = 20
[[menu.main]]
  identifier = "post"
  name = "ブログ"
  url = "/post/"
  weight = 40

[[menu.minecraft]]
  name = "サーバーへの接続方法"
  url = "/minecraft/how-to-connect/"
  weight = 10
[[menu.minecraft]]
  name = "アドオン入りワールド"
  url = "/minecraft/bob_2057/"
  weight = 20
[[menu.minecraft]]
  name = "フラットクリエイティブ"
  url = "/minecraft/creativeflatworld/"
  weight = 30
[[menu.minecraft]]
  name = "テスト中サーバ"
  url = "/minecraft/java02/"
  weight = 40

[params.ananke.home]
  content_alignment = "left"